### PR TITLE
ADBDEV-2753: Incorrect work bool data type in query to pxf foreign table 

### PR DESCRIPTION
**Pull request by RekGRpth**
Query on pxf external tables or pxf fdw does not correct work with bool variable pushdown. When pushdowning the results filtered twice: once - on remote pxf part and again - in local gpdb part. But if bool variable is not in select-statement and is in where-statement, then it is not returned from remote pxf part and local gpdb part can not filter by it. This leads to incorrect results.
Steps to reproduce this problem on external table:
```sql
create table tb_test_t(id serial primary key,  v_text text, v_bool bool);
insert into tb_test_t(v_text, v_bool) select v::text, false from generate_series(1, 20) v;
create extension pxf;
CREATE EXTERNAL TABLE tb_test_t_pxf(id int,  v_text text, v_bool bool) LOCATION('pxf://public.tb_test_t?PROFILE=JDBC') FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');
explain analyze select v_text from tb_test_t_pxf where v_text = '5' and  v_bool = false ;
select v_text from tb_test_t_pxf where v_text = '5' and  v_bool = false ;
                                                           QUERY PLAN                                                            
---------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..469.21 rows=237038 width=8) (actual time=100.480..100.480 rows=0 loops=1)
   ->  External Scan on tb_test_t_pxf  (cost=0.00..462.14 rows=79013 width=8) (never executed)
         Filter: ((v_text = '5'::text) AND (NOT v_bool))
 Planning time: 47.138 ms
   (slice0)    Executor memory: 132K bytes.
   (slice1)    Executor memory: 130K bytes avg x 3 workers, 130K bytes max (seg0).
 Memory used:  128000kB
 Optimizer: Pivotal Optimizer (GPORCA)
 Execution time: 107.201 ms
(9 rows)
INFO:  extractPxfAttributes: unsupported node tag 303, unable to extract attribute from qualifier  (seg0 slice1 172.19.0.2:5434 pid=7094)
CONTEXT:  External table tb_test_t_pxf
INFO:  extractPxfAttributes: unsupported node tag 303, unable to extract attribute from qualifier  (seg1 slice1 172.19.0.2:5435 pid=7095)
CONTEXT:  External table tb_test_t_pxf
INFO:  extractPxfAttributes: unsupported node tag 303, unable to extract attribute from qualifier  (seg2 slice1 172.19.0.2:5436 pid=7096)
CONTEXT:  External table tb_test_t_pxf
 v_text 
--------
(0 rows)
```
And on pxf fwd:
```sql
create extension pxf_fdw;
CREATE SERVER loopback FOREIGN DATA WRAPPER jdbc_pxf_fdw OPTIONS (jdbc_driver 'org.postgresql.Driver', db_url 'jdbc:postgresql://localhost:5432/gpdb');
CREATE USER MAPPING FOR CURRENT_USER SERVER loopback;
CREATE FOREIGN TABLE foreign_tb_test (id int,  v_text text, v_bool bool) SERVER loopback OPTIONS ( resource 'public.tb_test_t' );
explain analyze select v_text from foreign_tb_test where v_text = '5' and  v_bool = false ;
select v_text from foreign_tb_test where v_text = '5' and  v_bool = false ;
                                                              QUERY PLAN                                                              
--------------------------------------------------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=50000.00..50000.00 rows=1000 width=32) (actual time=124.892..124.892 rows=0 loops=1)
   ->  Foreign Scan on foreign_tb_test  (cost=50000.00..50000.00 rows=334 width=32) (never executed)
         Filter: ((NOT v_bool) AND (v_text = '5'::text))
 Planning time: 16.251 ms
   (slice0)    Executor memory: 59K bytes.
   (slice1)    Executor memory: 132K bytes avg x 3 workers, 138K bytes max (seg0).
 Memory used:  128000kB
 Optimizer: Postgres query optimizer
 Execution time: 125.806 ms
(9 rows)
 v_text 
--------
(0 rows)
```
This happens because `Filter: (NOT b2)` is `T_BoolExpr` consists of `T_Var` which is not supported by pxf pushdown (before this PR).

The problem for external tables was solved by adding `T_Var` for returning from pxf part, and for fdw was solved by setting WHERE clauses are OK on local.

Also a small bug in external tables (wrong total count of return values) was solved.

### CODE REVIEW

**Review by Stolb27 — CHANGES_REQUESTED** [review]
@RekGRpth, thank you for this patch.

It seems, that pushing down T_Var doesn't have side effects because T_Var may be part of T_OpExpr.

But, there is the similar code block and similar regression test case for foreign data wrapper interface [here](https://github.com/arenadata/pxf/blob/ac49d8fdca76a8b2d38037d2ff3a66b460b309ab/fdw/pxf_filter.c#L1502-L1584). Please fix it too. Steps to reproduce:

```sql
create extension pxf_fdw;
CREATE SERVER loopback 
 FOREIGN DATA WRAPPER jdbc_pxf_fdw
 OPTIONS ( 
     jdbc_driver 'org.postgresql.Driver', 
     db_url 'jdbc:postgresql://ivanov-test2.ru-central1.internal:6000/test',
     batch_size '10000',
     fetch_size '2000'
 );

CREATE FOREIGN TABLE foreign_tb_test (id int,  v_text text, v_bool bool)
  SERVER loopback
  OPTIONS ( resource 'public.tb_test_t' );

select v_text from foreign_tb_test where v_text = '5' and  v_bool = false ;
```

Also, please extend commit and PR description with the example of handling qual expression that shows how T_Var was generated.

**Comment by InnerLife0** [comment]
Overall OK, but I really miss commit, PR and test descriptions.
How's the bug looking? Was it an error or something? If error, it's a good practice to include it here and in the test comment.
The block of new tests is not divided and explained. To understand why we need this and what was the error, somebody will need to find commit description, which is not handy (despite the fact it missed explanation too).

**Comment by andr-sokolov** [comment]
It would be better to write without brackets, because in the case of T_Var local variables are not declared, and in one line, because, unlike neighboring cases, the line fits in 80 characters
```
            case T_Var:
                attributes = append_attr_from_var((Var*) node, attributes);
                break;
```

**Comment by RekGRpth** [comment]
> But, there is the similar code block and similar regression test case for foreign data wrapper interface [here](https://github.com/arenadata/pxf/blob/ac49d8fdca76a8b2d38037d2ff3a66b460b309ab/fdw/pxf_filter.c#L1502-L1584). Please fix it too. Steps to reproduce:
> 
> ```sql
> create extension pxf_fdw;
> CREATE SERVER loopback 
>  FOREIGN DATA WRAPPER jdbc_pxf_fdw
>  OPTIONS ( 
>      jdbc_driver 'org.postgresql.Driver', 
>      db_url 'jdbc:postgresql://ivanov-test2.ru-central1.internal:6000/test',
>      batch_size '10000',
>      fetch_size '2000'
>  );
> 
> CREATE FOREIGN TABLE foreign_tb_test (id int,  v_text text, v_bool bool)
>   SERVER loopback
>   OPTIONS ( resource 'public.tb_test_t' );
> 
> select v_text from foreign_tb_test where v_text = '5' and  v_bool = false ;
> ```

done

**Comment by InnerLife0** [comment]
> The block of new tests is not divided and explained. To understand why we need this and what was the error, somebody will need to find commit description, which is not handy (despite the fact it missed explanation too).

I still miss any general comment of why we need a copy of existing tests, but with different target list.
To not duplicate much, it may be placed somewhere in the beginning or even in commit/PR description.

**Comment by RekGRpth** [comment]
> I still miss any general comment of why we need a copy of existing tests, but with different target list.

Because if bool variable is not in select-statement and is in where-statement, then it is not returned from remote pxf part and local gpdb part can not filter by it.

**Comment by RekGRpth** [comment]
> > The block of new tests is not divided and explained. To understand why we need this and what was the error, somebody will need to find commit description, which is not handy (despite the fact it missed explanation too).
> 
> I still miss any general comment of why we need a copy of existing tests, but with different target list. To not duplicate much, it may be placed somewhere in the beginning or even in commit/PR description.

tests are rewrited

**Review by Stolb27 — APPROVED** [review]

**Pull request merged**
